server:
  port: 8080

spring:
  application:
    name: api-monitoring
  
  datasource:
    url: jdbc:h2:mem:monitoring
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    web:
      server:
        request:
          autotime:
            enabled: true

logging:
  level:
    com.example.apimonitoring: INFO
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

monitoring:
  check-interval: 30000  # 30 seconds
  timeout: 5000          # 5 seconds
  retry-attempts: 3
  ssl:
    ignore-certificate-errors: true  # TEMPORARILY ENABLED - Set to false for production